#!/bin/zsh

selected_dir="$(find /home/alzr7th/dox/ /home/alzr7th/work/ /home/alzr7th/personal/ /home/alzr7th/projects/ /home/alzr7th/.local/bin /home/alzr7th/.config -type d | fzf )"
if [ -n "$selected_dir" ]; then
  session_name="z_$(basename "$selected_dir")"
  if ! tmux has-session -t "$session_name" 2>/dev/null; then
    tmux new-session -d -s "$session_name" -c "$selected_dir" "zsh -i"
  fi
  tmux switch-client -t "$session_name"
fi

